#!/usr/bin/env python
from jamaendo.api import DB
import sys

def main():
    db = DB()
    print "Connecting to DB..."
    db.connect()
    print "Connected."
    q = sys.argv[1]
    print "Querying db for %s..." % (q)
    ids = db.search_artists(q)
    print ", ".join(ids)

if __name__=="__main__":
    main()
