#!/usr/bin/env python2.5

# Dependencies:

# python-simplejson
# python-lxml
# python-gst0.10


# debugging hack - add . to path
import os, sys
local_module_dir = os.path.join(os.path.dirname(sys.argv[0]), '..')
if os.path.isdir(local_module_dir):
    sys.path = [local_module_dir] + sys.path

def main():
    from jamaui.ui import Jamaui
    player = Jamaui()

    player.run()

if __name__=="__main__":
    main()
