#!/usr/bin/env python

# debugging hack - add . to path
import os, sys
local_module_dir = os.path.join(os.path.dirname(sys.argv[0]), '..')
if os.path.isdir(local_module_dir):
    sys.path.append(local_module_dir)

def main():
    from jamaui.ui import JamaUI
    player = JamaUI()
    player.run()

if __name__=="__main__":
    main()
