#!/usr/bin/env python
from jamaendo.api import refresh_dump
import locale, time

locale.setlocale(locale.LC_ALL, '')
code = locale.getpreferredencoding()

class Monitor(object):
    def __init__(self):
        self.done = False
        self.last_percent = 0
    def complete(self):
        print "Done."
        self.done = True
    def progress(self, percent):
        if percent - self.last_percent >= 5:
            print "%d%%" % (percent)
            self.last_percent = percent

def main():
    print "Updating jamendo DB dump..."
    monitor = Monitor()
    refresh_dump(monitor.complete, monitor.progress, force=False)
    while not monitor.done:
        time.sleep(1)

if __name__ == "__main__":
    main()
